Minor fixes to failures when running tests
Current code has various incorrectly formatted strings, this fixes all of them
and `make test` passed on my local go1.13.4

```
container/common/container_hints_test.go:30:3: Errorf format %s has arg cHints of wrong type github.com/google/cadvisor/container/common.containerHints
container/common/container_hints_test.go:47:4: Errorf format %s has arg cHints of wrong type github.com/google/cadvisor/container/common.containerHints

manager/watcher/raw/raw.go:90:5: Warningf call needs 1 arg but has 2 args

utils/oomparser/oomparser.go:143:2: missing ... in args forwarded to printf-like function
utils/oomparser/oomparser.go:146:2: missing ... in args forwarded to printf-like function
utils/oomparser/oomparser.go:149:2: missing ... in args forwarded to printf-like function
```

Signed-off-by: Daniel Dao <dqminh89@gmail.com>