Remove s390x support
We can't build with s390x now due to missing package
(thin-provisioning-tools)

```
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/s390x/APKINDEX.tar.gz
ERROR: unable to select packages:
thin-provisioning-tools (no such package):
required by: world[thin-provisioning-tools]
```

Signed-off-by: David Porter <david@porter.me>